// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations need a direct, non-pooled connection — Neon's pooled
    // connection doesn't reliably support the advisory lock `prisma migrate
    // deploy` takes, causing deploys to fail with a P1002 timeout. The app
    // itself (src/lib/db.ts) still connects with DATABASE_URL (pooled).
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
